---
name: WWW-Scraper-ISBN-AmazonDE_Driver
version: 0.1
author:
  - 'Renee Baecker <module@renee-baecker.de>'
abstract: Search driver for the (DE) Amazon online catalog.
license: artistic_2
resources:
  license: http://dev.perl.org/licenses/
requires:
  Web::Scraper 0.31
  WWW::Mechanize: 0
  WWW::Scraper::ISBN: 0
  WWW::Scraper::ISBN::Driver: 0
build_requires:
  Test::More: 0
  Web::Scraper 0.31
  WWW::Mechanize: 0
  WWW::Scraper::ISBN: 0
  WWW::Scraper::ISBN::Driver: 0
provides:
  WWW::Scraper::ISBN::AmazonDE_Driver:
    file: lib/WWW/Scraper/ISBN/AmazonDE_Driver.pm
    version: 0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
